### ISSUE TITLE
MacOS linker doesn't support --as-needed option

### ISSUE THREAD

**Issue by ul** [janestreet/jenga-rules#2]
Which is used here https://github.com/janestreet/jenga-rules/blob/master/lib/root.ml#L3724

```
(match Mode.which with
           | `Native -> ["-ccopt"; "-Wl,--as-needed"]
           | `Byte -> ["-custom"]);
```

Thus trying to build a project with `jane-build` fails with `ld: unknown option: --as-needed`

I understand that jenga-rules are Jenga rules used at Jane Street and they are not to be adapted for everyone's needs, but probably fixing that particular issue would be not very intrusive change.

**Comment by ghost** [comment]
indeed, do you think you could submit a PR? I think we have a binding for uname in Core. BTW the current plan is to write jenga rules that can interpret the rules of jbuilder, so that we have a set of jenga rules targeted at the opam world

**Comment by ul** [comment]
I think I'm too new in OCaml and its building process intrinsics to accomplish that task at the moment. For example, I don't know if it would be safe enough to just drop that option when building on MacOS or it requires crafting and inserting other options instead. Though I've build my small project with jenga-rules fork without `--as-needed` successfully.

Taking in account your last statement, could I propose to give this issue a chance to just float around for a while? If and when mentioned jenga-rules improvement will be delayed, I'll submit PR being more confident about its safety at that moment.

**Comment by thedufer** [comment]
I ran into this issue as well.  I put together a patch ([seen here](https://github.com/thedufer/jenga-rules/commit/af1339c69672d166c15b8b632105bb32029ad52f)), but I'm not sure how to go about testing it.  It builds using [make], but I'm not sure how to get [jane-build] to build against my jenga-rules instead of the opam one.

**Comment by ul** [comment]
I'll test it today, don't worry. And I think it's acceptable solution. I was using jenga-rules without --as-needed for some time and it seems to be harmless to just drop this option.

**Comment by ul** [comment]
But sorry for not answering your question. `opam pin add jenga-rules /path/to/your/jenga-rules` should help to build custom `jane-build`

**Comment by ul** [comment]
But "-Wl" itself looks like required.

**Comment by thedufer** [comment]
Ah, I see.  It worked without that on my test case, but I suspect it was too minimal. 

I just pushed a commit to add that back in, but it looks like you already have a PR.  Thanks!

**Comment by hhugo** [comment]
jenga-rules is no longer supported
