### ISSUE TITLE
Missing executable [gar]

### ISSUE THREAD

**Issue by thedufer** [janestreet/jenga-rules#4]
I'm using the same setup as in #3 - a library containing a single empty ml file and a simple jbuild.  I'm getting the error

`/Users/aarond/.opam/system/lib/jenga-rules/scripts/deterministic-ranlib/ar: line 16: gar: command not found`

It looks like it is trying to call `gar` because my uname reports "Darwin", but I don't have gar installed and it isn't a terribly searchable name.  What is that supposed to be?

I do have a `/usr/bin/ar` (the non-Darwin version) but it doesn't appear to take the flags that jenga is trying to pass in (specifically `-D`).  It looks like it is a BSD utility for creating/maintaining archives.  Do I just have the wrong version of what jenga is trying to call?  Or is this something else entirely?

**Comment by ghost** [comment]
Sorry the error is  not very helpful indeed. `gar` is "GNU ar". I think you can install it with homebrew

**Comment by thedufer** [comment]
Thanks! That was the hint I needed.  It is hidden in `brew install binutils` on OS X.
